# Generated by Django 2.1.5 on 2020-07-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=50)),
                ('description1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(default='', upload_to='uploads/products/')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='technical.Category')),
            ],
        ),
    ]
