# Generated by Django 2.1.5 on 2020-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0005_speaker_tv'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(default='', upload_to='uploads/products/')),
            ],
        ),
    ]
